a = input('Digite algo: ')
print(f'O tipo primitivo dsse valor é: {type(a)}')
print(f'Só tem espaços? {a.isspace()}')
print(f'é um número? {a.isnumeric()}')
print(f'é alfabético? {a.isalpha()}')
print(f'é alfanumérico? {a.isalnum()}')
print(f'Está em maiúsculas? {a.isupper()}')
print(f'Está em minúsculas? {a.islower()}')
print(f'Está capitalizada? {a.istitle()}')
